-- 1. Retrieve each film titles with their category, release_year and rating.
SELECT f.title, c.name, f.release_year, f.rating
FROM category c
JOIN film_category fc
USING(category_id)
JOIN film f
USING(film_id);

-- 2. Categories and the count of the movies those related to that category.
SELECT c.name, count(fc.film_id)
FROM category c
JOIN film_category fc
USING(category_id)
GROUP BY c.name;

-- 3. Calculate the total rental revenue generated by each film category.
SELECT c.name, count(r.rental_id) as total_rentals, sum(p.amount) as revenue
FROM category c
JOIN film_category fc
ON c.category_id=fc.category_id
JOIN inventory i
ON fc.film_id=i.film_id
JOIN rental r
ON i.inventory_id=r.inventory_id
JOIN payment p
ON r.rental_id=p.rental_id
GROUP BY c.name
ORDER BY revenue desc;

-- 4. Find the customers whose total spending is greater than average spending of customers who made at least one payment.
WITH temp as (
    SELECT customer_id, sum(amount) as total_spending
    FROM payment
    group by customer_id
)
SELECT CONCAT(c.first_name, ' ', c.last_name), t.total_spending
FROM customer c
JOIN temp t
ON c.customer_id=t.customer_id
WHERE total_spending >= (SELECT avg(total_spending) FROM temp)
ORDER BY t.total_spending desc;

-- 5. Rank all customers based on they spent.
SELECT c.customer_id, CONCAT(c.first_name, ' ', c.last_name) as full_name,
       sum(p.amount) as total_spend,
       RANK() OVER (ORDER BY sum(p.amount) desc) as rank
FROM payment p
JOIN customer c
ON p.customer_id=c.customer_id
GROUP BY c.customer_id, CONCAT(c.first_name, ' ', c.last_name)
ORDER BY rank;

-- 6. Total revenue of each month
SELECT EXTRACT(MONTH from p.payment_date) as month,
       EXTRACT(YEAR from p.payment_date) as year,
       SUM(p.amount) as total_revenue
FROM payment p
GROUP BY EXTRACT(MONTH from p.payment_date), EXTRACT(YEAR from p.payment_date)
ORDER BY year, month;

-- 7. Top 3 customers in each country who spent most.
WITH temp AS (
    SELECT c.customer_id,
           CONCAT(c.first_name, ' ', c.last_name) as customer_name,
           co.country as country,
           SUM(p.amount) AS total_spending,
           DENSE_RANK() OVER (PARTITION BY co.country ORDER BY SUM(amount) DESC) as rn
    FROM customer c
    JOIN payment p
    ON c.customer_id = p.customer_id
    JOIN address a
    ON c.address_id = a.address_id
    JOIN city ci
    ON a.city_id = ci.city_id
    JOIN country co
    ON ci.country_id = co.country_id
    GROUP BY c.customer_id, c.first_name, c.last_name, co.country
)
SELECT country, customer_name, total_spending, rn
FROM temp
WHERE rn<=3
ORDER BY country, rn;

-- 8. Actors who appear together more than 5 time
SELECT CONCAT(a1.first_name, ' ', a1.last_name) AS Actor1,
       CONCAT(a2.first_name, ' ', a2.last_name) AS Actor2,
       COUNT(*) AS together
FROM film_actor f1
JOIN film_actor f2
ON f1.film_id=f2.film_id
AND f1.actor_id<f2.actor_id
JOIN actor a1
ON f1.actor_id=a1.actor_id
JOIN actor a2
ON f2.actor_id=a2.actor_id
GROUP BY Actor1, Actor2
HAVING count(*)>5
ORDER BY together desc;

-- 9. Actors who appeared in more than 20 films
SELECT CONCAT(a.first_name, ' ', a.last_name),
       COUNT(fa.film_id) as films
FROM actor a
JOIN film_actor fa
ON a.actor_id = fa.actor_id
GROUP BY a.actor_id, a.first_name, a.last_name
HAVING COUNT(fa.film_id)>20
ORDER BY films desc;

-- 10. List the top 10 who have spent the most.
SELECT CONCAT(c.first_name, ' ', c.last_name) as customer_name,
       SUM(p.amount) AS total_spent
FROM customer c
JOIN payment p
ON c.customer_id = p.customer_id
GROUP BY customer_name
ORDER BY total_spent DESC
LIMIT 10;

